# Generated by Django 6.0.5 on 2026-06-08 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InActivo",
            fields=[
                ("nro_activo", models.AutoField(primary_key=True, serialize=False)),
                ("cod_activo", models.CharField(max_length=15, unique=True)),
                ("cod_activo_ax", models.IntegerField(blank=True, null=True)),
                ("nro_disp", models.IntegerField(blank=True, null=True)),
                ("descripcion", models.TextField()),
                (
                    "monto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("fec_adqui", models.DateField(blank=True, null=True)),
                ("nro_serie", models.CharField(blank=True, max_length=36, null=True)),
                ("cod_indus", models.IntegerField(blank=True, null=True)),
                ("tipo_garan", models.SmallIntegerField(blank=True, null=True)),
                ("doc_garan", models.CharField(blank=True, max_length=30, null=True)),
                ("fin_garan", models.DateField(blank=True, null=True)),
                ("tipo_trans", models.SmallIntegerField()),
                ("cod_trans", models.IntegerField()),
                ("fecha_trans", models.DateField()),
                ("a_b", models.CharField(max_length=1)),
                ("central", models.CharField(blank=True, max_length=1, null=True)),
                ("ok_rev", models.SmallIntegerField(blank=True, null=True)),
                ("nro_int", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "db_table": "in_activo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InAsignado",
            fields=[
                ("cod_asig", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_resp", models.SmallIntegerField()),
                ("cod_resp", models.IntegerField()),
                ("fecha_asig", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("obs", models.CharField(blank=True, max_length=170, null=True)),
                ("tipo_trans", models.SmallIntegerField()),
                ("cod_trans", models.IntegerField()),
                ("fecha_trans", models.DateField()),
                ("estado", models.CharField(max_length=1)),
                ("tipo_inv", models.SmallIntegerField(blank=True, null=True)),
                ("cod_inv", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "in_asignado",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InAtributo",
            fields=[
                ("cod_atrib", models.AutoField(primary_key=True, serialize=False)),
                ("des", models.CharField(max_length=30)),
                ("a_b", models.CharField(max_length=1)),
            ],
            options={
                "db_table": "in_atributo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InCondicion",
            fields=[
                (
                    "cod_cond",
                    models.SmallIntegerField(primary_key=True, serialize=False),
                ),
                ("des_cond", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "in_condicion",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InEstado",
            fields=[
                (
                    "cod_estado",
                    models.SmallIntegerField(primary_key=True, serialize=False),
                ),
                ("des_estado", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "in_estado",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InFuncionAdm",
            fields=[
                ("cod_func", models.IntegerField(primary_key=True, serialize=False)),
                ("des", models.CharField(max_length=50)),
                ("estprog", models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                "db_table": "in_funcion_adm",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InGestion",
            fields=[
                ("cod_gest", models.AutoField(primary_key=True, serialize=False)),
                ("gest_ini", models.SmallIntegerField()),
                ("gest_fin", models.SmallIntegerField(blank=True, null=True)),
                ("a_b", models.CharField(max_length=1)),
            ],
            options={
                "db_table": "in_gestion",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InIngreso",
            fields=[
                ("nro_ingreso", models.AutoField(primary_key=True, serialize=False)),
                ("gestion", models.SmallIntegerField(blank=True, null=True)),
                ("tipo_ingreso", models.IntegerField(blank=True, null=True)),
                ("tipo_recur", models.IntegerField(blank=True, null=True)),
                ("tipo_desc", models.IntegerField(blank=True, null=True)),
                ("acta_recep", models.CharField(blank=True, max_length=20, null=True)),
                ("fecha_recep", models.DateField(blank=True, null=True)),
                ("tipo_emp_recep", models.SmallIntegerField(blank=True, null=True)),
                ("cod_emp_recep", models.IntegerField(blank=True, null=True)),
                ("cod_cont", models.IntegerField(blank=True, null=True)),
                ("tipo_emp_dest", models.SmallIntegerField(blank=True, null=True)),
                ("cod_emp_dest", models.IntegerField(blank=True, null=True)),
                ("tipo_emp_codi", models.SmallIntegerField(blank=True, null=True)),
                ("cod_emp_codi", models.IntegerField(blank=True, null=True)),
                ("tipo_emp_enc", models.SmallIntegerField(blank=True, null=True)),
                ("cod_emp_enc", models.IntegerField(blank=True, null=True)),
                ("glosa", models.CharField(blank=True, max_length=72, null=True)),
                ("nro_compra", models.IntegerField(blank=True, null=True)),
                ("fecha_compra", models.DateField(blank=True, null=True)),
                ("nro_egreso", models.IntegerField(blank=True, null=True)),
                ("fecha_egreso", models.DateField(blank=True, null=True)),
                ("nro_factura", models.IntegerField(blank=True, null=True)),
                ("fecha_factura", models.DateField(blank=True, null=True)),
                ("nro_doc_rpa", models.IntegerField(blank=True, null=True)),
                ("fecha_doc_rpa", models.DateField(blank=True, null=True)),
                ("cod_trans", models.IntegerField()),
                ("tipo_trans", models.SmallIntegerField()),
                ("fecha_trans", models.DateTimeField(blank=True, null=True)),
                ("cod_gest", models.IntegerField(blank=True, null=True)),
                ("estado", models.CharField(blank=True, max_length=1, null=True)),
                ("cod_asig", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "in_ingreso",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InMarca",
            fields=[
                ("cod_marca", models.AutoField(primary_key=True, serialize=False)),
                ("des_marca", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "in_marca",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InMotivo",
            fields=[
                ("motivo", models.SmallIntegerField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "in_motivo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InOferta",
            fields=[
                ("nro_oferta", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_ofer", models.DateField()),
                ("glosa", models.CharField(max_length=40)),
                ("fecha", models.DateField()),
                ("cod_emp", models.IntegerField()),
                ("a_b", models.CharField(max_length=1)),
                ("estado", models.CharField(max_length=1)),
            ],
            options={
                "db_table": "in_oferta",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InParte",
            fields=[
                ("cod_parte", models.AutoField(primary_key=True, serialize=False)),
                ("des_parte", models.CharField(max_length=30)),
                ("a_b", models.CharField(max_length=1)),
            ],
            options={
                "db_table": "in_parte",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InProvedor",
            fields=[
                ("cod_prov", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=45)),
                ("direccion", models.CharField(blank=True, max_length=40, null=True)),
                ("telefono", models.CharField(blank=True, max_length=12, null=True)),
                ("fax", models.CharField(blank=True, max_length=12, null=True)),
                ("e_mail", models.CharField(blank=True, max_length=40, null=True)),
                ("ruc", models.CharField(blank=True, max_length=12, null=True)),
                ("ciudad", models.CharField(blank=True, max_length=25, null=True)),
                ("fecha_trans", models.DateField(blank=True, null=True)),
                ("tipo_trans", models.SmallIntegerField(blank=True, null=True)),
                ("cod_trans", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "in_provedor",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InResponsable",
            fields=[
                ("cod_resp", models.AutoField(primary_key=True, serialize=False)),
                ("cod_estprog", models.CharField(max_length=5)),
                ("cod_emp", models.IntegerField()),
                ("tipo_per", models.CharField(max_length=1)),
                ("fecha", models.DateField()),
                ("a_b", models.CharField(max_length=1)),
            ],
            options={
                "db_table": "in_responsable",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InRevaluo",
            fields=[
                ("cod_reval", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_reval", models.IntegerField()),
                ("documento", models.CharField(blank=True, max_length=50, null=True)),
                ("fecha_ini", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("estado", models.CharField(max_length=1)),
                ("tipo_trans", models.SmallIntegerField()),
                ("cod_trans", models.IntegerField()),
            ],
            options={
                "db_table": "in_revaluo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InTipo",
            fields=[
                (
                    "cod_tipo",
                    models.SmallIntegerField(primary_key=True, serialize=False),
                ),
                ("des_tipo", models.CharField(max_length=30)),
                ("a_b", models.CharField(max_length=1)),
            ],
            options={
                "db_table": "in_tipo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InTipoAsig",
            fields=[
                (
                    "tipo_asig",
                    models.SmallIntegerField(primary_key=True, serialize=False),
                ),
                ("des", models.CharField(max_length=50)),
                ("abrev", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "in_tipo_asig",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InTipoIng",
            fields=[
                ("tipo_ingreso", models.AutoField(primary_key=True, serialize=False)),
                ("des", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "in_tipo_ing",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InTipomat",
            fields=[
                ("tipo_mat", models.IntegerField(primary_key=True, serialize=False)),
                ("des_mat", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "in_tipomat",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InTipoReval",
            fields=[
                ("tipo_reval", models.IntegerField(primary_key=True, serialize=False)),
                ("des_reval", models.CharField(max_length=50)),
                ("a_b", models.CharField(max_length=1)),
            ],
            options={
                "db_table": "in_tipo_reval",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InUnidad",
            fields=[
                (
                    "cod_unidad",
                    models.SmallIntegerField(primary_key=True, serialize=False),
                ),
                ("des_unidad", models.CharField(max_length=20)),
                ("abrev", models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                "db_table": "in_unidad",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InBajaAct",
            fields=[
                ("nro", models.AutoField(primary_key=True, serialize=False)),
                ("cod_asig", models.IntegerField()),
                ("tipo_per_aut", models.SmallIntegerField()),
                ("cod_emp_aut", models.IntegerField()),
                ("documento", models.CharField(blank=True, max_length=100, null=True)),
                ("fecha_baja_te", models.DateField()),
                ("motivo", models.CharField(max_length=1)),
                ("fecha_baja_ef", models.DateField(blank=True, null=True)),
                (
                    "observacion",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("tipo_trans", models.SmallIntegerField(blank=True, null=True)),
                ("cod_trans", models.IntegerField(blank=True, null=True)),
                ("fecha_trans", models.DateTimeField(blank=True, null=True)),
                ("tipo_per_resp", models.SmallIntegerField(blank=True, null=True)),
                ("cod_emp_resp", models.IntegerField(blank=True, null=True)),
                (
                    "valor_final",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "nro_activo",
                    models.ForeignKey(
                        db_column="nro_activo",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inactivo",
                    ),
                ),
            ],
            options={
                "db_table": "in_baja_act",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="inactivo",
            name="cod_cond",
            field=models.ForeignKey(
                blank=True,
                db_column="cod_cond",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="activo.incondicion",
            ),
        ),
        migrations.CreateModel(
            name="InDetAtrib",
            fields=[
                ("cod_det_atrib", models.AutoField(primary_key=True, serialize=False)),
                ("nro_atrib", models.CharField(max_length=2)),
                ("des", models.CharField(max_length=30)),
                ("a_b", models.CharField(max_length=1)),
                (
                    "cod_atrib",
                    models.ForeignKey(
                        db_column="cod_atrib",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inatributo",
                    ),
                ),
            ],
            options={
                "db_table": "in_det_atrib",
                "managed": True,
                "unique_together": {("cod_atrib", "nro_atrib")},
            },
        ),
        migrations.CreateModel(
            name="InEncargado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_resp", models.SmallIntegerField()),
                ("cod_resp", models.IntegerField()),
                ("fecha_ini", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("tipo_trans", models.SmallIntegerField()),
                ("cod_trans", models.IntegerField()),
                ("fecha_trans", models.DateField()),
                (
                    "cod_asig",
                    models.ForeignKey(
                        db_column="cod_asig",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inasignado",
                    ),
                ),
            ],
            options={
                "db_table": "in_encargado",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="inactivo",
            name="cod_estado",
            field=models.ForeignKey(
                db_column="cod_estado",
                on_delete=django.db.models.deletion.PROTECT,
                to="activo.inestado",
            ),
        ),
        migrations.CreateModel(
            name="InEmpleado",
            fields=[
                ("codigo", models.AutoField(primary_key=True, serialize=False)),
                ("tipo", models.CharField(max_length=1)),
                ("nombre", models.CharField(max_length=40)),
                ("cod_emp", models.IntegerField(blank=True, null=True)),
                ("docto_idn", models.CharField(blank=True, max_length=12, null=True)),
                ("docto_idl", models.CharField(blank=True, max_length=3, null=True)),
                ("tipo_docid", models.CharField(blank=True, max_length=1, null=True)),
                ("fecha_ini", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("tipo_trans", models.SmallIntegerField()),
                ("cod_trans", models.IntegerField()),
                ("fecha_trans", models.DateField()),
                (
                    "cod_func",
                    models.ForeignKey(
                        db_column="cod_func",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.infuncionadm",
                    ),
                ),
            ],
            options={
                "db_table": "in_empleado",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="inactivo",
            name="cod_gest",
            field=models.ForeignKey(
                db_column="cod_gest",
                on_delete=django.db.models.deletion.PROTECT,
                to="activo.ingestion",
            ),
        ),
        migrations.CreateModel(
            name="InGrupo",
            fields=[
                ("cod_grupo", models.AutoField(primary_key=True, serialize=False)),
                ("cod_hijo", models.CharField(max_length=5)),
                ("des_grupo", models.CharField(blank=True, max_length=70, null=True)),
                ("nivel", models.SmallIntegerField(blank=True, null=True)),
                ("tipo_trans", models.SmallIntegerField(blank=True, null=True)),
                ("cod_trans", models.IntegerField(blank=True, null=True)),
                ("fecha_trans", models.DateField(blank=True, null=True)),
                ("a_b", models.CharField(max_length=1)),
                (
                    "cod_gest",
                    models.ForeignKey(
                        db_column="cod_gest",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.ingestion",
                    ),
                ),
                (
                    "cod_padre",
                    models.ForeignKey(
                        blank=True,
                        db_column="cod_padre",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hijos",
                        to="activo.ingrupo",
                    ),
                ),
                (
                    "cod_tipo",
                    models.ForeignKey(
                        blank=True,
                        db_column="cod_tipo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="activo.intipo",
                    ),
                ),
            ],
            options={
                "db_table": "in_grupo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InDetGrp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vida_util_mes", models.SmallIntegerField()),
                ("vida_util_ano", models.SmallIntegerField()),
                ("cuenta_cont", models.IntegerField()),
                ("cuenta_presup", models.IntegerField()),
                ("actualiza", models.CharField(blank=True, max_length=1, null=True)),
                ("revalua", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "cod_grupo",
                    models.ForeignKey(
                        db_column="cod_grupo",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.ingrupo",
                    ),
                ),
            ],
            options={
                "db_table": "in_det_grp",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="inatributo",
            name="cod_grupo",
            field=models.ForeignKey(
                db_column="cod_grupo",
                on_delete=django.db.models.deletion.PROTECT,
                to="activo.ingrupo",
            ),
        ),
        migrations.AddField(
            model_name="inactivo",
            name="cod_grupo",
            field=models.ForeignKey(
                db_column="cod_grupo",
                on_delete=django.db.models.deletion.PROTECT,
                to="activo.ingrupo",
            ),
        ),
        migrations.AddField(
            model_name="inactivo",
            name="nro_ingreso",
            field=models.ForeignKey(
                db_column="nro_ingreso",
                on_delete=django.db.models.deletion.PROTECT,
                to="activo.iningreso",
            ),
        ),
        migrations.AddField(
            model_name="inactivo",
            name="cod_marca",
            field=models.ForeignKey(
                blank=True,
                db_column="cod_marca",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="activo.inmarca",
            ),
        ),
        migrations.CreateModel(
            name="InModelo",
            fields=[
                ("cod_modelo", models.AutoField(primary_key=True, serialize=False)),
                ("des_modelo", models.CharField(max_length=30)),
                (
                    "cod_marca",
                    models.ForeignKey(
                        db_column="cod_marca",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inmarca",
                    ),
                ),
            ],
            options={
                "db_table": "in_modelo",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="inactivo",
            name="cod_modelo",
            field=models.ForeignKey(
                blank=True,
                db_column="cod_modelo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="activo.inmodelo",
            ),
        ),
        migrations.CreateModel(
            name="InDetOfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_material", models.IntegerField()),
                ("cantidad", models.SmallIntegerField()),
                ("monto_uni", models.DecimalField(decimal_places=2, max_digits=16)),
                ("id_marca", models.IntegerField()),
                ("id_modelo", models.IntegerField()),
                (
                    "nro_oferta",
                    models.ForeignKey(
                        db_column="nro_oferta",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inoferta",
                    ),
                ),
            ],
            options={
                "db_table": "in_det_ofer",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InOficina",
            fields=[
                ("cod_ofic", models.AutoField(primary_key=True, serialize=False)),
                ("cod_dpto", models.CharField(max_length=5)),
                ("des_dpto", models.CharField(max_length=70)),
                ("tipo_act", models.SmallIntegerField()),
                ("cod_activ", models.CharField(max_length=8)),
                ("nivel", models.SmallIntegerField()),
                ("cod_gest", models.IntegerField()),
                ("a_b", models.CharField(max_length=1)),
                (
                    "cod_padre",
                    models.ForeignKey(
                        blank=True,
                        db_column="cod_padre",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hijos",
                        to="activo.inoficina",
                    ),
                ),
            ],
            options={
                "db_table": "in_oficina",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="iningreso",
            name="cod_ofic_dest",
            field=models.ForeignKey(
                blank=True,
                db_column="cod_ofic_dest",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="activo.inoficina",
            ),
        ),
        migrations.AddField(
            model_name="inasignado",
            name="cod_ofic",
            field=models.ForeignKey(
                db_column="cod_ofic",
                on_delete=django.db.models.deletion.PROTECT,
                to="activo.inoficina",
            ),
        ),
        migrations.CreateModel(
            name="InDetParte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nro_serie", models.CharField(blank=True, max_length=20, null=True)),
                ("tamano", models.SmallIntegerField(blank=True, null=True)),
                ("cantidad", models.SmallIntegerField(blank=True, null=True)),
                ("tipo_det", models.IntegerField(blank=True, null=True)),
                ("vel_cap", models.SmallIntegerField(blank=True, null=True)),
                ("integrada", models.CharField(blank=True, max_length=1, null=True)),
                ("obs", models.CharField(blank=True, max_length=20, null=True)),
                ("nro_doc", models.IntegerField()),
                ("tipo_trans", models.SmallIntegerField()),
                ("cod_trans", models.IntegerField()),
                ("fecha_trans", models.DateField()),
                ("a_b", models.CharField(max_length=1)),
                (
                    "nro_activo",
                    models.ForeignKey(
                        db_column="nro_activo",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inactivo",
                    ),
                ),
                (
                    "cod_estado",
                    models.ForeignKey(
                        blank=True,
                        db_column="cod_estado",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="activo.inestado",
                    ),
                ),
                (
                    "cod_marca",
                    models.ForeignKey(
                        db_column="cod_marca",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inmarca",
                    ),
                ),
                (
                    "cod_modelo",
                    models.ForeignKey(
                        blank=True,
                        db_column="cod_modelo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="activo.inmodelo",
                    ),
                ),
                (
                    "cod_parte",
                    models.ForeignKey(
                        db_column="cod_parte",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inparte",
                    ),
                ),
            ],
            options={
                "db_table": "in_det_parte",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="inoferta",
            name="cod_prov",
            field=models.ForeignKey(
                db_column="cod_prov",
                on_delete=django.db.models.deletion.PROTECT,
                to="activo.inprovedor",
            ),
        ),
        migrations.AddField(
            model_name="iningreso",
            name="cod_prov",
            field=models.ForeignKey(
                blank=True,
                db_column="cod_prov",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="activo.inprovedor",
            ),
        ),
        migrations.AddField(
            model_name="inactivo",
            name="cod_prove",
            field=models.ForeignKey(
                blank=True,
                db_column="cod_prove",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="activo.inprovedor",
            ),
        ),
        migrations.CreateModel(
            name="InOrdenCompra",
            fields=[
                ("nro_compra", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_orden", models.DateField()),
                ("glosa", models.CharField(max_length=40)),
                ("nro_com_egre", models.IntegerField()),
                ("fecha", models.DateField()),
                ("cod_emp", models.IntegerField()),
                ("a_b", models.CharField(max_length=1)),
                (
                    "nro_oferta",
                    models.ForeignKey(
                        db_column="nro_oferta",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inoferta",
                    ),
                ),
                (
                    "emp_resp",
                    models.ForeignKey(
                        db_column="emp_resp",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inresponsable",
                    ),
                ),
            ],
            options={
                "db_table": "in_orden_compra",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InSolicitud",
            fields=[
                ("nro_sol", models.AutoField(primary_key=True, serialize=False)),
                ("gestion", models.SmallIntegerField()),
                ("cod_estprog", models.CharField(max_length=5)),
                ("glosa", models.CharField(max_length=50)),
                ("cod_emp", models.IntegerField()),
                ("fecha", models.DateField()),
                ("a_b", models.CharField(max_length=1)),
                (
                    "emp_resp",
                    models.ForeignKey(
                        db_column="emp_resp",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes_responsable",
                        to="activo.inresponsable",
                    ),
                ),
                (
                    "emp_sol",
                    models.ForeignKey(
                        db_column="emp_sol",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes_solicitante",
                        to="activo.inresponsable",
                    ),
                ),
            ],
            options={
                "db_table": "in_solicitud",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="inoferta",
            name="nro_sol",
            field=models.ForeignKey(
                db_column="nro_sol",
                on_delete=django.db.models.deletion.PROTECT,
                to="activo.insolicitud",
            ),
        ),
        migrations.CreateModel(
            name="InDetSol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_material", models.IntegerField()),
                ("cantidad", models.SmallIntegerField()),
                (
                    "nro_sol",
                    models.ForeignKey(
                        db_column="nro_sol",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.insolicitud",
                    ),
                ),
            ],
            options={
                "db_table": "in_det_sol",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="inasignado",
            name="tipo_asig",
            field=models.ForeignKey(
                db_column="tipo_asig",
                on_delete=django.db.models.deletion.PROTECT,
                to="activo.intipoasig",
            ),
        ),
        migrations.CreateModel(
            name="InTransferido",
            fields=[
                ("cod_transf", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_transf", models.CharField(blank=True, max_length=1, null=True)),
                ("cod_asig_or", models.IntegerField(blank=True, null=True)),
                ("cod_asig_de", models.IntegerField(blank=True, null=True)),
                ("cod_ofi_sol", models.IntegerField()),
                ("tipo_resp_sol", models.SmallIntegerField(blank=True, null=True)),
                ("cod_resp_sol", models.IntegerField(blank=True, null=True)),
                ("tipo_resp_rem", models.SmallIntegerField()),
                ("cod_resp_rem", models.IntegerField()),
                ("tipo_resp_dest", models.SmallIntegerField()),
                ("cod_resp_dest", models.IntegerField()),
                ("fecha_transf", models.DateField()),
                ("obs", models.CharField(blank=True, max_length=80, null=True)),
                ("tipo_trans", models.SmallIntegerField()),
                ("cod_trans", models.IntegerField()),
                ("fecha_trans", models.DateTimeField()),
                ("estado", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "cod_ofi_dest",
                    models.ForeignKey(
                        db_column="cod_ofi_dest",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_destino",
                        to="activo.inoficina",
                    ),
                ),
                (
                    "cod_ofi_rem",
                    models.ForeignKey(
                        db_column="cod_ofi_rem",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_remitente",
                        to="activo.inoficina",
                    ),
                ),
            ],
            options={
                "db_table": "in_transferido",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InDetTranf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(blank=True, null=True)),
                ("tipo_trans", models.SmallIntegerField()),
                ("cod_trans", models.IntegerField()),
                ("fecha_trans", models.DateTimeField(blank=True, null=True)),
                (
                    "nro_activo",
                    models.ForeignKey(
                        db_column="nro_activo",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inactivo",
                    ),
                ),
                (
                    "cod_transf",
                    models.ForeignKey(
                        db_column="cod_transf",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.intransferido",
                    ),
                ),
            ],
            options={
                "db_table": "in_det_tranf",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="inactivo",
            name="cod_unidad",
            field=models.ForeignKey(
                blank=True,
                db_column="cod_unidad",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="activo.inunidad",
            ),
        ),
        migrations.CreateModel(
            name="InDepAcumulada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nro_serie", models.IntegerField()),
                (
                    "depresiacion",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "acumulada",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "depres_ant",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "valor_actual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "valor_revaluo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "nro_activo",
                    models.ForeignKey(
                        db_column="nro_activo",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inactivo",
                    ),
                ),
            ],
            options={
                "db_table": "in_dep_acumulada",
                "managed": True,
                "unique_together": {("nro_serie", "nro_activo")},
            },
        ),
        migrations.CreateModel(
            name="InDetAsig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.SmallIntegerField()),
                ("fecha_trans", models.DateField()),
                ("tipo_trans", models.SmallIntegerField()),
                ("cod_trans", models.IntegerField()),
                (
                    "cod_asig",
                    models.ForeignKey(
                        db_column="cod_asig",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inasignado",
                    ),
                ),
                (
                    "nro_activo",
                    models.OneToOneField(
                        db_column="nro_activo",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inactivo",
                    ),
                ),
            ],
            options={
                "db_table": "in_det_asig",
                "managed": True,
                "unique_together": {("cod_asig", "nro_activo")},
            },
        ),
        migrations.CreateModel(
            name="InAtribActivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ok", models.CharField(max_length=1)),
                ("valor", models.CharField(max_length=25)),
                ("unidad", models.SmallIntegerField()),
                ("obs", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "nro_activo",
                    models.ForeignKey(
                        db_column="nro_activo",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inactivo",
                    ),
                ),
                (
                    "cod_det_atrib",
                    models.ForeignKey(
                        db_column="cod_det_atrib",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.indetatrib",
                    ),
                ),
            ],
            options={
                "db_table": "in_atrib_activo",
                "managed": True,
                "unique_together": {("cod_det_atrib", "nro_activo")},
            },
        ),
        migrations.CreateModel(
            name="InModGrp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a_b", models.CharField(max_length=1)),
                (
                    "cod_grupo",
                    models.ForeignKey(
                        db_column="cod_grupo",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.ingrupo",
                    ),
                ),
                (
                    "cod_marca",
                    models.ForeignKey(
                        db_column="cod_marca",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inmarca",
                    ),
                ),
                (
                    "cod_modelo",
                    models.ForeignKey(
                        db_column="cod_modelo",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inmodelo",
                    ),
                ),
            ],
            options={
                "db_table": "in_mod_grp",
                "managed": True,
                "unique_together": {("cod_modelo", "cod_marca", "cod_grupo")},
            },
        ),
        migrations.CreateModel(
            name="InParteGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cod_grupo",
                    models.ForeignKey(
                        db_column="cod_grupo",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.ingrupo",
                    ),
                ),
                (
                    "cod_parte",
                    models.ForeignKey(
                        db_column="cod_parte",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inparte",
                    ),
                ),
            ],
            options={
                "db_table": "in_parte_grupo",
                "managed": True,
                "unique_together": {("cod_parte", "cod_grupo")},
            },
        ),
        migrations.CreateModel(
            name="InContacto",
            fields=[
                ("cod_cont", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=45)),
                ("tipo_docid", models.CharField(max_length=1)),
                ("docto_idn", models.CharField(max_length=12)),
                ("docto_idl", models.CharField(max_length=3)),
                ("telefono", models.CharField(max_length=12)),
                ("fecha_trans", models.DateField(blank=True, null=True)),
                ("tipo_trans", models.SmallIntegerField(blank=True, null=True)),
                ("cod_trans", models.IntegerField(blank=True, null=True)),
                (
                    "cod_prov",
                    models.ForeignKey(
                        db_column="cod_prov",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inprovedor",
                    ),
                ),
            ],
            options={
                "db_table": "in_contacto",
                "managed": True,
                "unique_together": {("cod_prov", "docto_idn", "docto_idl")},
            },
        ),
        migrations.CreateModel(
            name="InDetReval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vida_util_mes", models.SmallIntegerField()),
                ("vida_util_ano", models.SmallIntegerField()),
                ("tipo_moneda", models.CharField(blank=True, max_length=1, null=True)),
                ("costo", models.DecimalField(decimal_places=2, max_digits=16)),
                ("fecha_reval", models.DateField()),
                ("serie_ant", models.IntegerField(blank=True, null=True)),
                ("tipo_trans", models.SmallIntegerField()),
                ("cod_trans", models.IntegerField()),
                ("fecha_trans", models.DateField()),
                ("serie", models.IntegerField()),
                ("estado", models.CharField(max_length=1)),
                ("tipo", models.SmallIntegerField(blank=True, null=True)),
                (
                    "nro_activo",
                    models.ForeignKey(
                        db_column="nro_activo",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inactivo",
                    ),
                ),
                (
                    "cod_reval",
                    models.ForeignKey(
                        db_column="cod_reval",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activo.inrevaluo",
                    ),
                ),
            ],
            options={
                "db_table": "in_det_reval",
                "managed": True,
                "unique_together": {("cod_reval", "nro_activo")},
            },
        ),
    ]
