# Generated by Django 6.0.6 on 2026-06-08 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='in_asignado',
            fields=[
                ('cod_asig', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_resp', models.SmallIntegerField()),
                ('cod_resp', models.IntegerField()),
                ('fecha_asig', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'in_asignado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_atributo',
            fields=[
                ('cod_atrib', models.AutoField(primary_key=True, serialize=False)),
                ('des', models.CharField(max_length=30)),
                ('a_b', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'in_atributo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_condicion',
            fields=[
                ('cod_cond', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('des_cond', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'in_condicion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_estado',
            fields=[
                ('cod_estado', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('des_estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'in_estado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_funcion_adm',
            fields=[
                ('cod_func', models.IntegerField(primary_key=True, serialize=False)),
                ('des', models.CharField(max_length=50)),
                ('estprog', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'in_funcion_adm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_gestion',
            fields=[
                ('cod_gest', models.AutoField(primary_key=True, serialize=False)),
                ('gest_ini', models.SmallIntegerField()),
                ('gest_fin', models.SmallIntegerField(blank=True, null=True)),
                ('a_b', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'in_gestion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_ingreso',
            fields=[
                ('nro_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('gestion', models.SmallIntegerField(blank=True, null=True)),
                ('tipo_ingreso', models.IntegerField(blank=True, null=True)),
                ('nro_compra', models.IntegerField(blank=True, null=True)),
                ('glosa', models.CharField(blank=True, max_length=72, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'in_ingreso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_marca',
            fields=[
                ('cod_marca', models.AutoField(primary_key=True, serialize=False)),
                ('des_marca', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'in_marca',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_parte',
            fields=[
                ('cod_parte', models.AutoField(primary_key=True, serialize=False)),
                ('des_parte', models.CharField(max_length=30)),
                ('a_b', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'in_parte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_provedor',
            fields=[
                ('cod_prov', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('direccion', models.CharField(blank=True, max_length=40, null=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('ruc', models.CharField(blank=True, max_length=12, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'in_provedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_responsable',
            fields=[
                ('cod_resp', models.AutoField(primary_key=True, serialize=False)),
                ('cod_estprog', models.CharField(max_length=5)),
                ('cod_emp', models.IntegerField()),
                ('tipo_per', models.CharField(max_length=1)),
                ('fecha', models.DateField()),
                ('a_b', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'in_responsable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_revaluo',
            fields=[
                ('cod_reval', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reval', models.IntegerField()),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'in_revaluo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_tipo',
            fields=[
                ('cod_tipo', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('des_tipo', models.CharField(max_length=30)),
                ('a_b', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'in_tipo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_tipo_asig',
            fields=[
                ('tipo_asig', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('des', models.CharField(max_length=50)),
                ('abrev', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'in_tipo_asig',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_tipomat',
            fields=[
                ('tipo_mat', models.IntegerField(primary_key=True, serialize=False)),
                ('des_mat', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'in_tipomat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_unidad',
            fields=[
                ('cod_unidad', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('des_unidad', models.CharField(max_length=20)),
                ('abrev', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'in_unidad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_det_atrib',
            fields=[
                ('cod_det_atrib', models.AutoField(primary_key=True, serialize=False)),
                ('nro_atrib', models.CharField(max_length=2)),
                ('des', models.CharField(max_length=30)),
                ('a_b', models.CharField(max_length=1)),
                ('cod_atrib', models.ForeignKey(db_column='cod_atrib', on_delete=django.db.models.deletion.PROTECT, to='activo.in_atributo')),
            ],
            options={
                'db_table': 'in_det_atrib',
                'managed': True,
                'unique_together': {('cod_atrib', 'nro_atrib')},
            },
        ),
        migrations.CreateModel(
            name='in_encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_resp', models.SmallIntegerField()),
                ('cod_resp', models.IntegerField()),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cod_asig', models.ForeignKey(db_column='cod_asig', on_delete=django.db.models.deletion.PROTECT, to='activo.in_asignado')),
            ],
            options={
                'db_table': 'in_encargado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_grupo',
            fields=[
                ('cod_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('cod_hijo', models.CharField(max_length=5)),
                ('des_grupo', models.CharField(blank=True, max_length=70, null=True)),
                ('nivel', models.SmallIntegerField(blank=True, null=True)),
                ('a_b', models.CharField(max_length=1)),
                ('cod_gest', models.ForeignKey(db_column='cod_gest', on_delete=django.db.models.deletion.PROTECT, to='activo.in_gestion')),
                ('cod_padre', models.ForeignKey(blank=True, db_column='cod_padre', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='activo.in_grupo')),
                ('cod_tipo', models.ForeignKey(blank=True, db_column='cod_tipo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='activo.in_tipo')),
            ],
            options={
                'db_table': 'in_grupo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_det_grp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vida_util_mes', models.SmallIntegerField()),
                ('vida_util_ano', models.SmallIntegerField()),
                ('cuenta_cont', models.IntegerField()),
                ('cuenta_presup', models.IntegerField()),
                ('cod_grupo', models.ForeignKey(db_column='cod_grupo', on_delete=django.db.models.deletion.PROTECT, to='activo.in_grupo')),
            ],
            options={
                'db_table': 'in_det_grp',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='in_atributo',
            name='cod_grupo',
            field=models.ForeignKey(db_column='cod_grupo', on_delete=django.db.models.deletion.PROTECT, to='activo.in_grupo'),
        ),
        migrations.CreateModel(
            name='in_modelo',
            fields=[
                ('cod_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('des_modelo', models.CharField(max_length=30)),
                ('cod_marca', models.ForeignKey(db_column='cod_marca', on_delete=django.db.models.deletion.PROTECT, to='activo.in_marca')),
            ],
            options={
                'db_table': 'in_modelo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_activo',
            fields=[
                ('nro_activo', models.AutoField(primary_key=True, serialize=False)),
                ('cod_activo', models.CharField(max_length=15, unique=True)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('fec_adqui', models.DateField(blank=True, null=True)),
                ('nro_serie', models.CharField(blank=True, max_length=36, null=True)),
                ('a_b', models.CharField(max_length=1)),
                ('cod_cond', models.ForeignKey(blank=True, db_column='cod_cond', null=True, on_delete=django.db.models.deletion.SET_NULL, to='activo.in_condicion')),
                ('cod_estado', models.ForeignKey(db_column='cod_estado', on_delete=django.db.models.deletion.PROTECT, to='activo.in_estado')),
                ('cod_gest', models.ForeignKey(db_column='cod_gest', on_delete=django.db.models.deletion.PROTECT, to='activo.in_gestion')),
                ('cod_grupo', models.ForeignKey(db_column='cod_grupo', on_delete=django.db.models.deletion.PROTECT, to='activo.in_grupo')),
                ('nro_ingreso', models.ForeignKey(db_column='nro_ingreso', on_delete=django.db.models.deletion.PROTECT, to='activo.in_ingreso')),
                ('cod_marca', models.ForeignKey(blank=True, db_column='cod_marca', null=True, on_delete=django.db.models.deletion.SET_NULL, to='activo.in_marca')),
                ('cod_modelo', models.ForeignKey(blank=True, db_column='cod_modelo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='activo.in_modelo')),
                ('cod_prove', models.ForeignKey(blank=True, db_column='cod_prove', null=True, on_delete=django.db.models.deletion.SET_NULL, to='activo.in_provedor')),
                ('cod_unidad', models.ForeignKey(blank=True, db_column='cod_unidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='activo.in_unidad')),
            ],
            options={
                'db_table': 'in_activo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_oficina',
            fields=[
                ('cod_ofic', models.AutoField(primary_key=True, serialize=False)),
                ('cod_dpto', models.CharField(max_length=20)),
                ('des_dpto', models.CharField(max_length=70)),
                ('tipo_act', models.SmallIntegerField()),
                ('cod_activ', models.CharField(max_length=8)),
                ('nivel', models.SmallIntegerField()),
                ('cod_gest', models.IntegerField()),
                ('a_b', models.CharField(max_length=1)),
                ('cod_padre', models.ForeignKey(blank=True, db_column='cod_padre', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='activo.in_oficina')),
            ],
            options={
                'db_table': 'in_oficina',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='in_ingreso',
            name='cod_ofic_dest',
            field=models.ForeignKey(blank=True, db_column='cod_ofic_dest', null=True, on_delete=django.db.models.deletion.SET_NULL, to='activo.in_oficina'),
        ),
        migrations.AddField(
            model_name='in_asignado',
            name='cod_ofic',
            field=models.ForeignKey(db_column='cod_ofic', on_delete=django.db.models.deletion.PROTECT, to='activo.in_oficina'),
        ),
        migrations.CreateModel(
            name='in_det_parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_serie', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad', models.SmallIntegerField()),
                ('nro_activo', models.ForeignKey(db_column='nro_activo', on_delete=django.db.models.deletion.PROTECT, to='activo.in_activo')),
                ('cod_estado', models.ForeignKey(db_column='cod_estado', on_delete=django.db.models.deletion.PROTECT, to='activo.in_estado')),
                ('cod_marca', models.ForeignKey(db_column='cod_marca', on_delete=django.db.models.deletion.PROTECT, to='activo.in_marca')),
                ('cod_modelo', models.ForeignKey(db_column='cod_modelo', on_delete=django.db.models.deletion.PROTECT, to='activo.in_modelo')),
                ('cod_parte', models.ForeignKey(db_column='cod_parte', on_delete=django.db.models.deletion.PROTECT, to='activo.in_parte')),
            ],
            options={
                'db_table': 'in_det_parte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_oferta',
            fields=[
                ('nro_oferta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ofer', models.DateField()),
                ('glosa', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=1)),
                ('cod_prov', models.ForeignKey(db_column='cod_prov', on_delete=django.db.models.deletion.PROTECT, to='activo.in_provedor')),
            ],
            options={
                'db_table': 'in_oferta',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='in_ingreso',
            name='cod_prov',
            field=models.ForeignKey(blank=True, db_column='cod_prov', null=True, on_delete=django.db.models.deletion.SET_NULL, to='activo.in_provedor'),
        ),
        migrations.CreateModel(
            name='in_contacto',
            fields=[
                ('cod_cont', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('tipo_docid', models.CharField(max_length=1)),
                ('docto_idn', models.CharField(max_length=12)),
                ('docto_idl', models.CharField(max_length=3)),
                ('telefono', models.CharField(max_length=12)),
                ('cod_prov', models.ForeignKey(db_column='cod_prov', on_delete=django.db.models.deletion.PROTECT, to='activo.in_provedor')),
            ],
            options={
                'db_table': 'in_contacto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_orden_compra',
            fields=[
                ('nro_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_orden', models.DateField()),
                ('glosa', models.CharField(max_length=40)),
                ('nro_com_egre', models.IntegerField()),
                ('a_b', models.CharField(max_length=1)),
                ('nro_oferta', models.ForeignKey(db_column='nro_oferta', on_delete=django.db.models.deletion.PROTECT, to='activo.in_oferta')),
                ('emp_resp', models.ForeignKey(db_column='emp_resp', on_delete=django.db.models.deletion.PROTECT, to='activo.in_responsable')),
            ],
            options={
                'db_table': 'in_orden_compra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_solicitud',
            fields=[
                ('nro_sol', models.AutoField(primary_key=True, serialize=False)),
                ('gestion', models.SmallIntegerField()),
                ('cod_estprog', models.CharField(max_length=5)),
                ('glosa', models.CharField(max_length=50)),
                ('cod_emp', models.IntegerField()),
                ('fecha', models.DateField()),
                ('a_b', models.CharField(max_length=1)),
                ('emp_resp', models.ForeignKey(db_column='emp_resp', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_responsable', to='activo.in_responsable')),
                ('emp_sol', models.ForeignKey(db_column='emp_sol', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_solicitante', to='activo.in_responsable')),
            ],
            options={
                'db_table': 'in_solicitud',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='in_oferta',
            name='nro_sol',
            field=models.ForeignKey(db_column='nro_sol', on_delete=django.db.models.deletion.PROTECT, to='activo.in_solicitud'),
        ),
        migrations.AddField(
            model_name='in_asignado',
            name='tipo_asig',
            field=models.ForeignKey(db_column='tipo_asig', on_delete=django.db.models.deletion.PROTECT, to='activo.in_tipo_asig'),
        ),
        migrations.CreateModel(
            name='in_transferido',
            fields=[
                ('cod_transf', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_transf', models.CharField(max_length=1)),
                ('cod_asig_or', models.IntegerField(blank=True, null=True)),
                ('cod_asig_de', models.IntegerField(blank=True, null=True)),
                ('fecha_transf', models.DateField()),
                ('estado', models.CharField(max_length=1)),
                ('cod_ofi_dest', models.ForeignKey(db_column='cod_ofi_dest', on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_destino', to='activo.in_oficina')),
                ('cod_ofi_rem', models.ForeignKey(db_column='cod_ofi_rem', on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_remitente', to='activo.in_oficina')),
            ],
            options={
                'db_table': 'in_transferido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_det_tranf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('nro_activo', models.ForeignKey(db_column='nro_activo', on_delete=django.db.models.deletion.PROTECT, to='activo.in_activo')),
                ('cod_transf', models.ForeignKey(db_column='cod_transf', on_delete=django.db.models.deletion.PROTECT, to='activo.in_transferido')),
            ],
            options={
                'db_table': 'in_det_tranf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='in_dep_acumulada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_serie', models.IntegerField()),
                ('depresiacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acumulada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_revaluo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nro_activo', models.ForeignKey(db_column='nro_activo', on_delete=django.db.models.deletion.PROTECT, to='activo.in_activo')),
            ],
            options={
                'db_table': 'in_dep_acumulada',
                'managed': True,
                'unique_together': {('nro_serie', 'nro_activo')},
            },
        ),
        migrations.CreateModel(
            name='in_det_asig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.SmallIntegerField()),
                ('fecha_trans', models.DateField()),
                ('cod_asig', models.ForeignKey(db_column='cod_asig', on_delete=django.db.models.deletion.PROTECT, to='activo.in_asignado')),
                ('nro_activo', models.ForeignKey(db_column='nro_activo', on_delete=django.db.models.deletion.PROTECT, to='activo.in_activo')),
            ],
            options={
                'db_table': 'in_det_asig',
                'managed': True,
                'unique_together': {('cod_asig', 'nro_activo')},
            },
        ),
        migrations.CreateModel(
            name='in_atrib_activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.CharField(max_length=1)),
                ('valor', models.CharField(max_length=25)),
                ('unidad', models.SmallIntegerField()),
                ('nro_activo', models.ForeignKey(db_column='nro_activo', on_delete=django.db.models.deletion.PROTECT, to='activo.in_activo')),
                ('cod_det_atrib', models.ForeignKey(db_column='cod_det_atrib', on_delete=django.db.models.deletion.PROTECT, to='activo.in_det_atrib')),
            ],
            options={
                'db_table': 'in_atrib_activo',
                'managed': True,
                'unique_together': {('cod_det_atrib', 'nro_activo')},
            },
        ),
        migrations.CreateModel(
            name='in_mod_grp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_b', models.CharField(max_length=1)),
                ('cod_grupo', models.ForeignKey(db_column='cod_grupo', on_delete=django.db.models.deletion.PROTECT, to='activo.in_grupo')),
                ('cod_marca', models.ForeignKey(db_column='cod_marca', on_delete=django.db.models.deletion.PROTECT, to='activo.in_marca')),
                ('cod_modelo', models.ForeignKey(db_column='cod_modelo', on_delete=django.db.models.deletion.PROTECT, to='activo.in_modelo')),
            ],
            options={
                'db_table': 'in_mod_grp',
                'managed': True,
                'unique_together': {('cod_modelo', 'cod_marca', 'cod_grupo')},
            },
        ),
        migrations.CreateModel(
            name='in_det_ofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_material', models.IntegerField()),
                ('cantidad', models.SmallIntegerField()),
                ('monto_uni', models.DecimalField(decimal_places=2, max_digits=16)),
                ('id_marca', models.IntegerField()),
                ('id_modelo', models.IntegerField()),
                ('nro_oferta', models.ForeignKey(db_column='nro_oferta', on_delete=django.db.models.deletion.PROTECT, to='activo.in_oferta')),
            ],
            options={
                'db_table': 'in_det_ofer',
                'managed': True,
                'unique_together': {('nro_oferta', 'id_material')},
            },
        ),
        migrations.CreateModel(
            name='in_parte_grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_grupo', models.ForeignKey(db_column='cod_grupo', on_delete=django.db.models.deletion.PROTECT, to='activo.in_grupo')),
                ('cod_parte', models.ForeignKey(db_column='cod_parte', on_delete=django.db.models.deletion.PROTECT, to='activo.in_parte')),
            ],
            options={
                'db_table': 'in_parte_grupo',
                'managed': True,
                'unique_together': {('cod_parte', 'cod_grupo')},
            },
        ),
        migrations.CreateModel(
            name='in_det_reval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vida_util_mes', models.SmallIntegerField()),
                ('vida_util_ano', models.SmallIntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fecha_reval', models.DateField()),
                ('estado', models.CharField(max_length=1)),
                ('nro_activo', models.ForeignKey(db_column='nro_activo', on_delete=django.db.models.deletion.PROTECT, to='activo.in_activo')),
                ('cod_reval', models.ForeignKey(db_column='cod_reval', on_delete=django.db.models.deletion.PROTECT, to='activo.in_revaluo')),
            ],
            options={
                'db_table': 'in_det_reval',
                'managed': True,
                'unique_together': {('cod_reval', 'nro_activo')},
            },
        ),
        migrations.CreateModel(
            name='in_det_sol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_material', models.IntegerField()),
                ('cantidad', models.SmallIntegerField()),
                ('nro_sol', models.ForeignKey(db_column='nro_sol', on_delete=django.db.models.deletion.PROTECT, to='activo.in_solicitud')),
            ],
            options={
                'db_table': 'in_det_sol',
                'managed': True,
                'unique_together': {('nro_sol', 'id_material')},
            },
        ),
    ]
