# Generated by Django 6.0.6 on 2026-06-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_grupo',
            name='cod_hijo',
            field=models.CharField(max_length=20),
        ),
    ]
