# Generated by Django 6.0.6 on 2026-06-08 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activo', '0002_alter_in_grupo_cod_hijo'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'in_permiso',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='in_rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'in_rol',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='in_empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carné de Extranjería'), ('PASAPORTE', 'Pasaporte')], max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('foto', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Foto')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('id_empleado_jefe', models.ForeignKey(blank=True, db_column='id_empleado_jefe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='activo.in_empleado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'in_empleado',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='in_responsable',
            name='cod_emp',
            field=models.ForeignKey(db_column='cod_emp', on_delete=django.db.models.deletion.PROTECT, to='activo.in_empleado'),
        ),
        migrations.AlterField(
            model_name='in_solicitud',
            name='cod_emp',
            field=models.ForeignKey(db_column='cod_emp', on_delete=django.db.models.deletion.PROTECT, to='activo.in_empleado'),
        ),
        migrations.CreateModel(
            name='in_usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=20)),
                ('otp_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('id_empleado', models.OneToOneField(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='activo.in_empleado')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'in_usuario',
                'ordering': ['correo'],
            },
        ),
        migrations.CreateModel(
            name='in_rol_permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='activo.in_permiso')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='activo.in_rol')),
            ],
            options={
                'verbose_name': 'Rol Permiso',
                'verbose_name_plural': 'Roles Permisos',
                'db_table': 'in_rol_permiso',
                'unique_together': {('id_rol', 'id_permiso')},
            },
        ),
        migrations.CreateModel(
            name='in_rol_permiso_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('id_permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_roles', to='activo.in_permiso')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_permisos', to='activo.in_rol')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='roles_permisos', to='activo.in_usuario')),
            ],
            options={
                'verbose_name': 'Rol Permiso Usuario',
                'verbose_name_plural': 'Roles Permisos Usuarios',
                'db_table': 'in_rol_permiso_usuario',
                'unique_together': {('id_usuario', 'id_rol', 'id_permiso')},
            },
        ),
    ]
