# Generated by Django 6.0.6 on 2026-06-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activo", "0002_rename_inactivo_activo_rename_inasignado_asignado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oficina",
            name="cod_dpto",
            field=models.CharField(max_length=20),
        ),
    ]
