# Generated by Django 6.0.5 on 2026-06-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activo", "0003_in_permiso_in_rol_in_empleado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="in_ingreso",
            name="acta_recep",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="in_ingreso",
            name="cod_emp_dest",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="in_ingreso",
            name="cod_emp_recep",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="in_ingreso",
            name="fecha_egreso",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="in_ingreso",
            name="fecha_factura",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="in_ingreso",
            name="fecha_recep",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="in_ingreso",
            name="nro_egreso",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="in_ingreso",
            name="nro_factura",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="in_ingreso",
            name="tipo_emp_dest",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="in_ingreso",
            name="tipo_emp_recep",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
