# Generated by Django 6.0.6 on 2026-06-09 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activo', '0004_in_ingreso_acta_recep_in_ingreso_cod_emp_dest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_det_tranf',
            name='cod_trans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='in_det_tranf',
            name='fecha_trans',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='in_det_tranf',
            name='tipo_trans',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='in_revaluo',
            name='documento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
