# Generated by Django 6.0.6 on 2026-06-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activo', '0006_in_log_activo_in_log_asignado_in_log_baja_act_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_activo',
            name='cod_rube',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='in_activo',
            name='estado_registro',
            field=models.CharField(default='ELABORADO', max_length=20),
        ),
        migrations.AddField(
            model_name='in_activo',
            name='nro_convenio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='in_activo',
            name='organismo_financiador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='in_empleado',
            name='procedencia',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Procedencia'),
        ),
    ]
